# Generated by Django 3.2.4 on 2021-08-11 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations

import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0012_alter_transfer_schema_change_3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationfee",
            name="charge",
            field=djstripe.fields.StripeForeignKey(
                blank=True,
                help_text="The charge that the application fee was taken from.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="djstripe.charge",
                to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD,
            ),
        ),
    ]
