# Generated by Django 3.2.11 on 2022-02-01 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0012_alter_subscription_latest_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='latest_invoice',
        ),
    ]
