# Generated by Django 3.2.4 on 2021-06-25 14:50

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0015_alter_applicationfee_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='latest_invoice',
            field=djstripe.fields.StripeForeignKey(blank=True, help_text='The most recent invoice this subscription has generated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='djstripe.invoice', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD),
        ),
    ]
